// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-a3j1M9Q7vrUTwdNGMhFurM4AM7vJdKg',
    appId: '1:486896924349:web:9009592036d942e49c29d4',
    messagingSenderId: '486896924349',
    projectId: 'barberaplication-dfb56',
    authDomain: 'barberaplication-dfb56.firebaseapp.com',
    storageBucket: 'barberaplication-dfb56.firebasestorage.app',
    measurementId: 'G-QKYCD3F2J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgCyz5EnLPWZp9Y7JQlP1Bsbsk0Q5y3pE',
    appId: '1:486896924349:android:43d15f921c7eb4b69c29d4',
    messagingSenderId: '486896924349',
    projectId: 'barberaplication-dfb56',
    storageBucket: 'barberaplication-dfb56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Svh6srWyrJmd_bAfAFr5QtKld2m809w',
    appId: '1:486896924349:ios:aaf5a250b3b37fdd9c29d4',
    messagingSenderId: '486896924349',
    projectId: 'barberaplication-dfb56',
    storageBucket: 'barberaplication-dfb56.firebasestorage.app',
    iosBundleId: 'com.example.barberrApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Svh6srWyrJmd_bAfAFr5QtKld2m809w',
    appId: '1:486896924349:ios:aaf5a250b3b37fdd9c29d4',
    messagingSenderId: '486896924349',
    projectId: 'barberaplication-dfb56',
    storageBucket: 'barberaplication-dfb56.firebasestorage.app',
    iosBundleId: 'com.example.barberrApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-a3j1M9Q7vrUTwdNGMhFurM4AM7vJdKg',
    appId: '1:486896924349:web:21d9065d3e72b0e89c29d4',
    messagingSenderId: '486896924349',
    projectId: 'barberaplication-dfb56',
    authDomain: 'barberaplication-dfb56.firebaseapp.com',
    storageBucket: 'barberaplication-dfb56.firebasestorage.app',
    measurementId: 'G-9PGX53S1MF',
  );
}
